// Navegação, biblioteca, simulador, análise educativa, quiz e checklist.
'use strict';
const $=s=>document.querySelector(s);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const pageNames={inicio:'Início',biblioteca:'Biblioteca de golpes',simulador:'Simulador',analisador:'Analisador educativo',quiz:'Quiz',checklist:'Checklist',ajuda:'Caí em um golpe'};
function navigate(focus=false){let id=location.hash.slice(1)||'inicio';if(!pageNames[id])id='inicio';document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==id);document.querySelectorAll('.nav a').forEach(a=>{if(a.hash==='#'+id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});document.title=pageNames[id]+' | Escudo Digital';if(focus){$('#main').focus({preventScroll:true});window.scrollTo(0,0)}}
window.addEventListener('hashchange',()=>navigate(true));navigate();
const scams=[
{title:'Falsa central de atendimento',tag:'CONTAS E SENHAS',body:'Alguém se apresenta como funcionário do banco e diz que houve uma movimentação suspeita.',sign:'Pede senha, código de autenticação, instalação de aplicativo ou transferência para uma “conta segura”.',action:'Encerre a conversa e contate o banco pelo aplicativo oficial ou pelo número do seu cartão.'},
{title:'O familiar com número novo',tag:'MENSAGENS',body:'Um perfil usa a foto de uma pessoa conhecida, diz que trocou de número e pede dinheiro.',sign:'Solicitação urgente, recusa em conversar por ligação e pagamento para uma terceira pessoa.',action:'Confirme por um contato que você já tinha salvo. Não confie apenas na foto ou no nome.'},
{title:'Loja e oferta falsas',tag:'COMPRAS',body:'Uma oferta muito atraente leva a uma loja falsa ou a um perfil que imita uma marca.',sign:'Preço muito abaixo do comum, pressão para pagar e endereço que não corresponde ao site esperado.',action:'Confira a loja por fontes independentes e acesse o site oficial por conta própria. HTTPS sozinho não prova honestidade.'},
{title:'Entrega com taxa surpresa',tag:'LINKS E COBRANÇAS',body:'Um SMS ou e-mail informa que uma encomenda está retida e exige uma taxa para liberá-la.',sign:'Link inesperado, cobrança com prazo curto e falta de correspondência com seus pedidos.',action:'Consulte o pedido no aplicativo da loja ou no canal oficial da transportadora, sem usar o link recebido.'},
{title:'Prêmio ou renda garantida',tag:'PROMESSAS',body:'A mensagem oferece um prêmio, rendimento garantido ou dinheiro fácil por tarefas simples.',sign:'Exige depósito antecipado, promete retorno exagerado ou cobra novas taxas para liberar um saque.',action:'Não pague para receber um prêmio inesperado. Verifique a empresa e a proposta de forma independente.'},
{title:'Comprovante de Pix falso',tag:'PAGAMENTOS',body:'O comprador apresenta uma imagem de comprovante para convencer você a liberar um produto.',sign:'O valor não aparece no extrato; a imagem pode ter sido alterada ou mostrar apenas um agendamento.',action:'Confirme o crédito dentro do aplicativo do seu banco. Uma imagem ou notificação enviada por outra pessoa não comprova recebimento.'}
];
function renderLibrary(){const term=normalize($('#search').value.trim());const list=scams.filter(s=>normalize(Object.values(s).join(' ')).includes(term));$('#library-grid').innerHTML=list.map(s=>`<article class="card"><span class="tag">${s.tag}</span><h3>${s.title}</h3><p>${s.body}</p><details><summary>Sinais e como se proteger</summary><p><strong>Observe:</strong> ${s.sign}</p><p><strong>Como agir:</strong> ${s.action}</p></details></article>`).join('')||'<p class="empty">Nenhum exemplo encontrado. Tente “senha”, “Pix” ou “compra”.</p>';$('#library-count').textContent=list.length+' de '+scams.length+' exemplos';}$('#search').addEventListener('input',renderLibrary);renderLibrary();
const messages=[
{from:'SMS · suposto banco',text:'URGENTE: sua conta será bloqueada em 10 minutos. Confirme sua senha em https://acesso-banco.example para evitar o bloqueio.',bad:true,why:'A ameaça de bloqueio tenta apressar sua decisão. O pedido de senha e o endereço recebido são sinais de alerta. Abra o aplicativo do banco por conta própria.'},
{from:'Grupo de estudos',text:'Oi, pessoal! A reunião de revisão continua marcada para amanhã, às 14h, na biblioteca. O material está no ambiente da disciplina que já usamos.',bad:false,why:'O texto não pede dinheiro, senha ou acesso a um endereço novo. Não há indícios evidentes neste exemplo, mas isso não autentica quem enviou a mensagem.'},
{from:'Número não salvo',text:'Mãe, troquei de número! Preciso de um Pix de R$ 850 agora para pagar uma conta. Não consigo atender ligação. Manda para a conta do meu amigo?',bad:true,why:'Número novo, pressa, recusa de ligação e conta de terceiro formam um conjunto de alertas. Confirme a identidade pelo número antigo ou por outro canal conhecido.'},
{from:'SMS · entrega',text:'Sua encomenda está retida! Pague a taxa hoje em entrega-liberada.example para evitar a devolução.',bad:true,why:'A cobrança inesperada e a pressão para usar um link recebido merecem atenção. Consulte o rastreamento diretamente no serviço oficial.'},
{from:'Contato de um colega',text:'Você pode conferir o horário da aula no portal da faculdade? Acho que a turma mudou de sala.',bad:false,why:'A mensagem sugere consultar um canal já conhecido, sem pedir dados ou pagamentos. Não há sinais evidentes no texto; continue verificando o contexto.'}
];
let simIndex=0,simScore=0,simAnswered=false;
function renderSim(){simAnswered=false;const box=$('#simulation');if(simIndex===messages.length){box.innerHTML=`<div class="eyebrow">Prática concluída</div><h2>Seu olhar está mais atento.</h2><div class="score">${simScore}/${messages.length}</div><p>Classificações esperadas identificadas. Continue conferindo o contexto e o remetente fora da mensagem.</p><div class="actions"><button class="btn" id="sim-restart">Praticar novamente</button><a class="btn secondary" href="#quiz">Fazer o quiz →</a></div>`;$('#sim-restart').onclick=()=>{simIndex=0;simScore=0;renderSim()};return;}const m=messages[simIndex];box.innerHTML=`<div class="progress-top"><span>Mensagem ${simIndex+1} de ${messages.length}</span><span>Exemplo fictício</span></div><div class="progress"><span style="width:${simIndex/messages.length*100}%"></span></div><h2>${m.from}</h2><div class="message">${escapeHTML(m.text)}</div><p class="small muted" style="margin-top:18px">Qual é a sua leitura desta mensagem?</p><div class="actions"><button class="btn" data-answer="bad">Há sinais de golpe</button><button class="btn secondary" data-answer="normal">Sem indícios evidentes</button></div><div id="sim-feedback" aria-live="polite"></div>`;box.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(simAnswered)return;simAnswered=true;const correct=(b.dataset.answer==='bad')===m.bad;if(correct)simScore++;box.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);$('#sim-feedback').innerHTML=`<div class="feedback ${correct?'':'bad'}"><h3>${correct?'Boa leitura!':'Vamos observar mais de perto.'}</h3><p>${m.why}</p></div><button class="btn" id="sim-next" style="margin-top:18px">${simIndex===messages.length-1?'Ver resultado':'Próxima mensagem →'}</button>`;$('#sim-next').onclick=()=>{simIndex++;renderSim()};});}renderSim();
const rules=[{title:'Pressão e urgência',pattern:/urgente|imediat|\bagora\b|\bhoje\b|minutos|bloquead|suspens|ultima chance/,why:'Pressa pode reduzir o tempo para você conferir a história. Pare e confirme por outro canal.'},{title:'Pedido ou menção a credenciais',pattern:/senha|codigo|token|cvv|verificacao|autenticacao/,why:'Senhas e códigos podem dar acesso à sua conta. Não os compartilhe com alguém que entrou em contato.'},{title:'Pagamento ou transferência',pattern:/\bpix\b|deposit|transfer|pague|pagamento|taxa|boleto/,why:'Confira o motivo da cobrança e o beneficiário em canais independentes antes de pagar.'},{title:'Promessa de benefício',pattern:/premio|ganhou|sorteio|renda|retorno garantido|dinheiro facil|recompensa/,why:'Prêmios inesperados e ganhos garantidos podem ser usados como isca, especialmente se exigirem pagamento.'},{title:'Endereço presente no texto',pattern:/https?:\/\/|www\.|\b[a-z0-9-]+\.(?:com|net|org|br|xyz|top|example)\b/,why:'A presença de um endereço não confirma fraude nem segurança. Esta ferramenta não abre ou verifica links.'},{title:'Troca de contato ou acesso remoto',pattern:/troquei de numero|numero novo|novo numero|instal|acesso remoto|compartilh.*tela/,why:'Confirme mudanças de número por outro meio. Aplicativos de acesso remoto podem permitir que outra pessoa controle seu dispositivo.'}];
$('#analysis-form').onsubmit=e=>{e.preventDefault();const text=normalize($('#message-input').value.trim());if(!text){$('#analysis-result').innerHTML='<p class="feedback">Digite uma mensagem para analisar.</p>';return;}const hits=rules.filter(r=>r.pattern.test(text));$('#analysis-result').innerHTML=`<div class="feedback"><h3>${hits.length?hits.length+' categoria(s) de atenção encontrada(s)':'Nenhum padrão das regras foi identificado'}</h3><p>${hits.length?'Estes pontos merecem uma conferência. Não são uma confirmação de golpe.':'A ausência de padrões não significa segurança. Golpes também podem usar linguagem comum.'}</p></div>${hits.map(r=>`<div class="rule"><strong>${r.title}</strong><p>${r.why}</p></div>`).join('')}<p class="small muted" style="margin-top:18px">Confirme o contexto e o remetente por um canal oficial. Resultado produzido por regras locais, sem inteligência artificial.</p>`;};$('#example').onclick=()=>{$('#message-input').value=messages[0].text;$('#analysis-result').replaceChildren();$('#message-input').focus()};$('#clear-analysis').onclick=()=>{$('#message-input').value='';$('#analysis-result').replaceChildren();$('#message-input').focus()};$('#message-input').addEventListener('input',()=>$('#analysis-result').replaceChildren());
const questions=[
{q:'Uma pessoa do “suporte” pede o código que acabou de chegar por SMS. O que fazer?',options:['Informar o código para agilizar o atendimento.','Não compartilhar e procurar o suporte pelo canal oficial.','Enviar apenas metade do código.'],correct:1,why:'Códigos de autenticação podem autorizar acesso ou operações. Não compartilhe com quem entrou em contato com você.'},
{q:'Um site tem cadeado e HTTPS. Isso significa que a loja é confiável?',options:['Sim, o cadeado garante que a empresa é legítima.','Sim, se o preço também estiver baixo.','Não. HTTPS protege a conexão, mas sites fraudulentos também podem usá-lo.'],correct:2,why:'Uma conexão criptografada não comprova a honestidade do site. Confira endereço, reputação e dados da loja por fontes independentes.'},
{q:'Um familiar pede um Pix por um número novo. Qual é a melhor primeira ação?',options:['Confirmar com o familiar por um canal que você já conhece.','Transferir um valor menor como teste.','Confiar se a foto de perfil for a mesma.'],correct:0,why:'Foto e nome podem ser copiados. A confirmação por um canal independente ajuda a verificar quem realmente está pedindo.'},
{q:'Qual prática ajuda a proteger suas contas?',options:['Usar a mesma senha forte em todos os serviços.','Usar senhas diferentes e ativar a verificação em duas etapas.','Guardar todas as senhas em uma publicação privada.'],correct:1,why:'Senhas diferentes limitam os efeitos de um vazamento. Um gerenciador de senhas pode ajudar, e a segunda etapa adiciona proteção.'},
{q:'Você percebeu que fez um Pix após ser enganado. O que priorizar?',options:['Pagar alguém que promete recuperar tudo.','Esperar para ver se a pessoa devolve.','Contatar imediatamente o banco pelo canal oficial e contestar a transação.'],correct:2,why:'O banco pode orientar e avaliar o caso pelo MED quando aplicável. Guarde as evidências. A devolução não é garantida.'}
];let quizIndex=0,quizScore=0,quizAnswered=false;
function renderQuiz(){quizAnswered=false;const box=$('#quiz-panel');if(quizIndex===questions.length){box.innerHTML=`<div class="eyebrow">Quiz concluído</div><h2>${quizScore>=4?'Ótimo caminho!':'Cada resposta é um aprendizado.'}</h2><div class="score">${quizScore}/${questions.length}</div><p>${quizScore>=4?'Você reconheceu a maioria das boas práticas. Transforme esse conhecimento em ações.':'Revise os exemplos na biblioteca e experimente novamente quando quiser.'}</p><div class="actions"><button class="btn" id="quiz-restart">Refazer quiz</button><a class="btn secondary" href="#checklist">Ir para o checklist →</a></div>`;$('#quiz-restart').onclick=()=>{quizIndex=0;quizScore=0;renderQuiz()};return;}const q=questions[quizIndex];box.innerHTML=`<div class="progress-top"><span>Pergunta ${quizIndex+1} de ${questions.length}</span><span>Sem pressa para aprender</span></div><div class="progress"><span style="width:${quizIndex/questions.length*100}%"></span></div><h2 class="question">${q.q}</h2><div class="options">${q.options.map((o,i)=>`<button class="option" data-option="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div><div id="quiz-feedback" aria-live="polite"></div>`;box.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{if(quizAnswered)return;quizAnswered=true;const correct=Number(b.dataset.option)===q.correct;if(correct)quizScore++;box.querySelectorAll('[data-option]').forEach(x=>{x.disabled=true;if(Number(x.dataset.option)===q.correct)x.classList.add('correct')});if(!correct)b.classList.add('wrong');$('#quiz-feedback').innerHTML=`<div class="feedback ${correct?'':'bad'}"><h3>${correct?'Resposta correta!':'Resposta esperada: '+String.fromCharCode(65+q.correct)}</h3><p>${q.why}</p></div><button class="btn" id="quiz-next" style="margin-top:18px">${quizIndex===questions.length-1?'Ver meu resultado':'Próxima pergunta →'}</button>`;$('#quiz-next').onclick=()=>{quizIndex++;renderQuiz()};});}renderQuiz();
const checks=[['Uso senhas diferentes para cada conta','Evito que uma senha vazada comprometa outros serviços.'],['Ativei a verificação em duas etapas','Principalmente no e-mail, nas redes sociais e nos aplicativos que oferecem o recurso.'],['Mantenho sistema e aplicativos atualizados','Ativo atualizações automáticas quando possível.'],['Confiro pedidos de dinheiro por outro canal','Não dependo apenas do nome e da foto do contato.'],['Reviso sessões e dispositivos conectados','Encerro acessos desconhecidos nas configurações das minhas contas.'],['Mantenho cópias de segurança','Faço backup dos arquivos importantes e verifico se consigo recuperá-los.'],['Reviso permissões de aplicativos','Removo aplicativos que não uso e acessos desnecessários.'],['Conheço os canais oficiais de ajuda','Sei onde contatar meu banco e recuperar minhas principais contas.']];
const storageKey='escudo-digital-checklist-v1';let saved=[],storageAvailable=true;try{const parsed=JSON.parse(localStorage.getItem(storageKey)||'[]');if(Array.isArray(parsed))saved=parsed.filter(i=>Number.isInteger(i)&&i>=0&&i<checks.length)}catch(e){storageAvailable=false}saved=[...new Set(saved)];
function updateCheck(){const n=saved.length;$('#check-score').textContent=n+'/'+checks.length;$('#check-caption').textContent=n===checks.length?'Todas as medidas marcadas. Revise seus hábitos periodicamente.':n+' medida(s) adotada(s). Escolha a próxima ação no seu ritmo.';$('#check-progress').setAttribute('aria-valuenow',n);$('#check-progress span').style.width=n/checks.length*100+'%';$('#storage-note').textContent=storageAvailable?'Progresso salvo apenas neste navegador. Ao abrir em outro navegador, mover o arquivo ou limpar os dados, ele pode não estar disponível.':'Não foi possível salvar no navegador. Seu progresso será mantido apenas enquanto esta página estiver aberta.';$('#reset-check').disabled=n===0;}
function saveCheck(){try{localStorage.setItem(storageKey,JSON.stringify(saved));storageAvailable=true}catch(e){storageAvailable=false}updateCheck()}
$('#check-list').innerHTML=checks.map((c,i)=>`<label class="check-row"><input type="checkbox" value="${i}" ${saved.includes(i)?'checked':''}><span><strong>${c[0]}</strong><small>${c[1]}</small></span></label>`).join('');$('#check-list').addEventListener('change',()=>{saved=[...$('#check-list').querySelectorAll('input:checked')].map(x=>Number(x.value));saveCheck()});$('#reset-check').onclick=()=>{saved=[];$('#check-list').querySelectorAll('input').forEach(x=>x.checked=false);saveCheck()};updateCheck();
